### ISSUE TITLE
different user, different resin amount?

### ISSUE THREAD

**Issue by Cylcia-N3K0** [JDCRamos8/ResinManagerApp#1]
i want to deploy your application on my discord server, in the server not only me who play genshin and i want my friends can track their resin with only one discord bot. maybe simple txt file that store user_id and resin amount?

**Comment by ZyrexFX** [comment]
It's not that simple to store the database. U can use MongoDB for example to store the user's data.

**Comment by JDCRamos8** [comment]
Added database to store user data, yet calling a function many times causes duplicate instances of a user in database

**Comment by JDCRamos8** [comment]
Added MonogoDB to store user data, yet calling a function many times causes duplicate instances of a user in database
